site_name: NBIS Reproducible research course
theme: mkdocs
pages:
  - 'Introduction': 'index.md'
  - 'Conda': 'conda.md'
  - 'Snakemake': 'snakemake.md'
  - 'Git': 'git.md'
  - 'R Markdown': 'rmarkdown.md'
  - 'Jupyter': 'jupyter.md'
  - 'Docker': 'docker.md'
  - 'Take down': take_down.md
markdown_extensions:
  - toc:
      permalink: ÔÉÅ
  - admonition
  - pymdownx.arithmatex
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
extra_css: [extra.css]
