site_name: NBIS Reproducible research course
theme:
    name: readthedocs
    custom_dir: docs_custom/
pages:
  - Welcome: 'index.md'
  - About: 'about.md'
  - Practicalities:
    - Schedule: 'schedule.md'
    - 'Travel info': 'travel.md'
    - Feedback: 'feedback.html'
  - Lectures: 'lectures.md'
  - Tutorials:
    - 'Introduction to the tutorials': 'tutorial_intro.md'
    - Git: 'git.md'
    - Conda: 'conda.md'
    - Snakemake: 'snakemake.md'
    - R Markdown: 'rmarkdown.md'
    - Jupyter: 'jupyter.md'
    - Docker: 'docker.md'
    - Singularity: 'singularity.md'
    - 'Making a project reproducible': 'repres_project.md'
    - 'Take down': 'take_down.md'

markdown_extensions:
  - toc:
      permalink: ÔÉÅ
  - admonition
  - pymdownx.arithmatex
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
extra_css: [extra.css]
