name: snakemake-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.6
  - fastqc=0.11.9
  - sra-tools=2.10.1
  - snakemake-minimal=6.10.0
  - multiqc=1.10.1
  - bowtie2=2.4.4
  - tbb=2020.3
  - samtools=1.12
  - subread=2.0.1
  - graphviz=2.42.3
  - wget=1.20.1
  - xorg-libxrender
  - xorg-libxpm
