name: snakemake-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - fastqc
  - seqtk
  - snakemake
  - multiqc
  - bowtie2
  - tbb
  - samtools
  - subread>=2
  - bedtools
  - graphviz
  - wget
  - xorg-libxrender
  - xorg-libxpm
