name: git-env
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python=3.10.10
  - fastqc=0.11.9
  - seqtk=1.3
  - snakemake=7.25.0
  - multiqc=1.14
  - bowtie2=2.5.1
  - tbb=2021.8.0
  - samtools=1.16
  - subread=2.0.3
  - bedtools=2.30.0
  - r-base=4.1.3
  - r-ggplot2=3.4.2
  - r-reshape2=1.4.4
  - r-stringi=1.7.12
  - r-pheatmap=1.0.12
  - r-rmarkdown=2.13
  - r-r.utils=2.12.2
  - bioconductor-rtracklayer=1.54.0
  - bioconductor-geoquery=2.62.0
  - wget
  - graphviz
  - xorg-libxrender
  - xorg-libxpm
