name: git-env
channels:
  - conda-forge
  - bioconda
  - main
  - r
dependencies:
  - python=3.9.12
  - fastqc=0.11.9
  - sra-tools=2.11.0
  - snakemake=7.18.2
  - multiqc=1.12
  - bowtie2=2.4.5
  - tbb=2020.2
  - samtools=1.15.1
  - subread=2.0.1
  - bedtools=2.29.2
  - wget=1.20.3
  - graphviz=3.0.0
  - r-base=4.1.3
  - r-ggplot2=3.3.5
  - r-reshape2=1.4.4
  - r-stringi=1.7.6
  - r-pheatmap=1.0.12
  - r-rmarkdown=2.13
  - r-r.utils=2.11.0
  - bioconductor-rtracklayer=1.54.0
  - bioconductor-geoquery=2.62.0
  - xorg-libxrender
  - xorg-libxpm
