name: lectures

channels:
    - conda-forge
    - defaults
    - r

dependencies:

    # Jupyter
    - python=3.8
    - jupyter=1.0
    - pandas=1.0
    - rise=5.6
    - seaborn=0.10
    - rpy2=3.1

    # R and Xaringan
    - r-base=3.6
    - r-ggplot2=3.3
    - r-kableextra=1.1
    - r-xaringan=0.15
