name: rmarkdown-env
channels:
  - r
  - conda-forge
  - bioconda
  - main
dependencies:
  - bioconductor-geoquery=2.54.0
  - bioconductor-rtracklayer=1.46.0
  - r-base=3.6.1
  - r-devtools=2.4.0
  - r-ggplot2=3.3.3
  - r-networkd3=0.4
  - r-pheatmap=1.0.12
  - r-reshape2=1.4.4
  - r-rmarkdown=2.7
  - r-stringi=1.4.3
  - rstudio=1.1.456
