name: setup

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the main branch
on: workflow_dispatch
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        env: [snakemake, jupyter, rmarkdown]
        include:
          - os: macos-latest
            url: https://repo.continuum.io/miniconda/Miniconda3-4.7.12.1-MacOSX-x86_64.sh
          - os: ubuntu-latest
            url: https://repo.continuum.io/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh
          - env: snakemake
            cmd: snakemake --version
          - env: jupyter
            cmd: jupyter --version
          - env: rmarkdown
            cmd: Rscript --version
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: ${{ matrix.url }}
          activate-environment: ${{ matrix.env }}-env
          environment-file: ${{ matrix.env }}/environment.yml
          auto-activate-base: false
      - run: |
          conda list
          ${{ matrix.cmd }}